[Dummy13]
name="Dummy/1.3GHz"
type="Dummy"
f0=1.3e9
hbw=65

[Dummy39]
name="Dummy/3.9GHz"
type="Dummy"
f0=3.9e9
hbw=195

[DummyLong]
name="Dummy/Long"
type="Dummy"
hbw=10.8
f0=1.3e9
fs=1e5
flattop_start=2e-2
decay_start=2.7e-1
decay_stop=3e-1
klfd=0.0
det0=0.0

[CMTBSCAVC1]
name="CMTB/SCAV/C1"
type="DesyDoocsSCAV"
address="CMTB.RF/LLRF.CONTROLLER/CTRL.SCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C12.MTS.PROBE/CH0.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBSCAVC2]
name="CMTB/SCAV/C2"
type="DesyDoocsSCAV"
address="CMTB.RF/LLRF.CONTROLLER/CTRL.SCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C12.MTS.PROBE/CH1.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBSCAVC3]
name="CMTB/SCAV/C3"
type="DesyDoocsSCAV"
address="CMTB.RF/LLRF.CONTROLLER/CTRL.SCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C34.MTS.PROBE/CH0.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBSCAVC4]
name="CMTB/SCAV/C4"
type="DesyDoocsSCAV"
address="CMTB.RF/LLRF.CONTROLLER/CTRL.SCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C34.MTS.PROBE/CH1.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBSCAVC5]
name="CMTB/SCAV/C5"
type="DesyDoocsSCAV"
address="CMTB.RF/LLRF.CONTROLLER/CTRL.SCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C56.MTS.PROBE/CH0.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBSCAVC6]
name="CMTB/SCAV/C6"
type="DesyDoocsSCAV"
address="CMTB.RF/LLRF.CONTROLLER/CTRL.SCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C56.MTS.PROBE/CH1.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBSCAVC7]
name="CMTB/SCAV/C7"
type="DesyDoocsSCAV"
address="CMTB.RF/LLRF.CONTROLLER/CTRL.SCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C78.MTS.PROBE/CH0.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBSCAVC8]
name="CMTB/SCAV/C8"
type="DesyDoocsSCAV"
address="CMTB.RF/LLRF.CONTROLLER/CTRL.SCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C78.MTS.PROBE/CH1.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBMCAVC1]
name="CMTB/MCAV/C1"
type="DesyDoocsMCAV"
address="CMTB.RF/LLRF.CONTROLLER/C1.M1.MCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C12.MTS.PROBE/CH0.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBMCAVC2]
name="CMTB/MCAV/C2"
type="DesyDoocsMCAV"
address="CMTB.RF/LLRF.CONTROLLER/C2.M1.MCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C12.MTS.PROBE/CH1.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBMCAVC3]
name="CMTB/MCAV/C3"
type="DesyDoocsMCAV"
address="CMTB.RF/LLRF.CONTROLLER/C3.M1.MCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C34.MTS.PROBE/CH0.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBMCAVC4]
name="CMTB/MCAV/C4"
type="DesyDoocsMCAV"
address="CMTB.RF/LLRF.CONTROLLER/C4.M1.MCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C34.MTS.PROBE/CH1.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBMCAVC5]
name="CMTB/MCAV/C5"
type="DesyDoocsMCAV"
address="CMTB.RF/LLRF.CONTROLLER/C5.M1.MCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C56.MTS.PROBE/CH0.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBMCAVC6]
name="CMTB/MCAV/C6"
type="DesyDoocsMCAV"
address="CMTB.RF/LLRF.CONTROLLER/C6.M1.MCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C56.MTS.PROBE/CH1.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBMCAVC7]
name="CMTB/MCAV/C7"
type="DesyDoocsMCAV"
address="CMTB.RF/LLRF.CONTROLLER/C7.M1.MCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C78.MTS.PROBE/CH0.VALUE.VPM"
gradient_meter_normalization=1e-6

[CMTBMCAVC8]
name="CMTB/MCAV/C8"
type="DesyDoocsMCAV"
address="CMTB.RF/LLRF.CONTROLLER/C8.M1.MCAV.CMTB/"
gradient_meter_address="TTF.RF/GPIB/C78.MTS.PROBE/CH1.VALUE.VPM"
gradient_meter_normalization=1e-6

[AMTF39SCAVC1]
name="AMTF39/SCAV/C1"
type="DesyDoocsSCAV"
address="AMTF.RF/LLRF.CONTROLLER/CTRL.AMTF39CW/"
gradient_meter_address="AMTF.RF/RADIPOWER/C1.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF39SCAVC2]
name="AMTF39/SCAV/C2"
type="DesyDoocsSCAV"
address="AMTF.RF/LLRF.CONTROLLER/CTRL.AMTF39CW/"
gradient_meter_address="AMTF.RF/RADIPOWER/C2.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF39SCAVC3]
name="AMTF39/SCAV/C3"
type="DesyDoocsSCAV"
address="AMTF.RF/LLRF.CONTROLLER/CTRL.AMTF39CW/"
gradient_meter_address="AMTF.RF/RADIPOWER/C3.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF39SCAVC4]
name="AMTF39/SCAV/C4"
type="DesyDoocsSCAV"
address="AMTF.RF/LLRF.CONTROLLER/CTRL.AMTF39CW/"
gradient_meter_address="AMTF.RF/RADIPOWER/C4.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF39SCAVC5]
name="AMTF39/SCAV/C5"
type="DesyDoocsSCAV"
address="AMTF.RF/LLRF.CONTROLLER/CTRL.AMTF39CW/"
gradient_meter_address="AMTF.RF/RADIPOWER/C5.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF39SCAVC6]
name="AMTF39/SCAV/C6"
type="DesyDoocsSCAV"
address="AMTF.RF/LLRF.CONTROLLER/CTRL.AMTF39CW/"
gradient_meter_address="AMTF.RF/RADIPOWER/C6.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF39SCAVC7]
name="AMTF39/SCAV/C7"
type="DesyDoocsSCAV"
address="AMTF.RF/LLRF.CONTROLLER/CTRL.AMTF39CW/"
gradient_meter_address="AMTF.RF/RADIPOWER/C7.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF39SCAVC8]
name="AMTF39/SCAV/C8"
type="DesyDoocsSCAV"
address="AMTF.RF/LLRF.CONTROLLER/CTRL.AMTF39CW/"
gradient_meter_address="AMTF.RF/RADIPOWER/C8.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF391]
name="AMTF39/C1"
type="DesyDoocs
address="AMTF.RF/LLRF.CONTROLLER/C1.M1.AMTF39/"
gradient_meter_address="AMTF.RF/RADIPOWER/C1.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF392]
name="AMTF39/C2"
type="DesyDoocs
address="AMTF.RF/LLRF.CONTROLLER/C2.M1.AMTF39/"
gradient_meter_address="AMTF.RF/RADIPOWER/C2.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF393]
name="AMTF39/C3"
type="DesyDoocs
address="AMTF.RF/LLRF.CONTROLLER/C3.M1.AMTF39/"
gradient_meter_address="AMTF.RF/RADIPOWER/C3.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF394]
name="AMTF39/C4"
type="DesyDoocs
address="AMTF.RF/LLRF.CONTROLLER/C4.M1.AMTF39/"
gradient_meter_address="AMTF.RF/RADIPOWER/C4.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF395]
name="AMTF39/C5"
type="DesyDoocs
address="AMTF.RF/LLRF.CONTROLLER/C5.M1.AMTF39/"
gradient_meter_address="AMTF.RF/RADIPOWER/C5.MTS1.PROBE/POWER.VPM"
radient_meter_normalization=1e-6

[AMTF396]
name="AMTF39/C6"
type="DesyDoocs
address="AMTF.RF/LLRF.CONTROLLER/C6.M1.AMTF39/"
gradient_meter_address="AMTF.RF/RADIPOWER/C6.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF397]
name="AMTF39/C7"
type="DesyDoocs
address="AMTF.RF/LLRF.CONTROLLER/C7.M1.AMTF39/"
gradient_meter_address="AMTF.RF/RADIPOWER/C7.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[AMTF398]
name="AMTF39/C8"
type="DesyDoocs
address="AMTF.RF/LLRF.CONTROLLER/C8.M1.AMTF39/"
gradient_meter_address="AMTF.RF/RADIPOWER/C8.MTS1.PROBE/POWER.VPM"
gradient_meter_normalization=1e-6

[CMTBCHIMERATK]
name="CMTB/ChimeraTK"
type="ChimeraTK"
dmap_file="file.dmap"
device_name="cmtb_scav"
probe_amp_address="PROBE.SCAV.CMTB/AMPL"
probe_pha_address="PROBE.SCAV.CMTB/PHASE"
vforw_amp_address="FORWARD.SCAV.CMTB/AMPL"
vforw_pha_address="FORWARD.SCAV.CMTB/PHASE"
vrefl_amp_address="REFLECTED.SCAV.CMTB/AMPL"
vrefl_pha_address="REFLECTED.SCAV.CMTB/PHASE"
probe_cal_amp_address="PROBE.SCAV.CMTB/CAL_SCA"
probe_cal_pha_address="PROBE.SCAV.CMTB/CAL_ROT"
vforw_cal_amp_address="FORWARD.SCAV.CMTB/CAL_SCA"
vforw_cal_pha_address="FORWARD.SCAV.CMTB/CAL_ROT"
vrefl_cal_amp_address="REFLECTED.SCAV.CMTB/CAL_SCA"
vrefl_cal_pha_address="REFLECTED.SCAV.CMTB/CAL_ROT"
pulse_delay_address="CTRL.SCAV.CMTB/PULSE_DELAY"
pulse_filling_address="CTRL.SCAV.CMTB/PULSE_FILLING"
pulse_flattop_address="CTRL.SCAV.CMTB/PULSE_FLATTOP"
decoupling_a_re_address="CTRL.SCAV.CMTB/DECOUPLING.A_RE"
decoupling_a_im_address="CTRL.SCAV.CMTB/DECOUPLING.A_IM"
decoupling_b_re_address="CTRL.SCAV.CMTB/DECOUPLING.B_RE"
decoupling_b_im_address="CTRL.SCAV.CMTB/DECOUPLING.B_IM"
decoupling_c_re_address="CTRL.SCAV.CMTB/DECOUPLING.C_RE"
decoupling_c_im_address="CTRL.SCAV.CMTB/DECOUPLING.C_IM"
decoupling_d_re_address="CTRL.SCAV.CMTB/DECOUPLING.D_RE"
decoupling_d_im_address="CTRL.SCAV.CMTB/DECOUPLING.D_IM"
ql_address="CTRL.SCAV.CMTB/QL"
f0_address="CTRL.SCAV.CMTB/F0"
fs_address="CTRL.SCAV.CMTB/FS"
