[Dummy13]
name="Dummy/1.3GHz"
type="Dummy"
f0=1.3e9
hbw=65

[Dummy39]
name="Dummy/3.9GHz"
type="Dummy"
f0=3.9e9
hbw=195

[DummyLong]
name="Dummy/Long"
type="Dummy"
hbw=10.8
f0=1.3e9
fs=1e5
flattop_start=2e-2
decay_start=2.7e-1
decay_stop=3e-1
klfd=0.0
det0=0.0
